/*********************************************************************************
Class Name: DocumentController

Purpose:    1. This is the class to get the notes and attachments associated group, company and plant

Please maintain only the last 5 history changes/modifications in the audit log

History of Changes:                
--------------------------------------------------------------------------------------------------------------------------
Date                                          Developer                               Comments
--------------------------------------------------------------------------------------------------------------------------
24-01-2024                                    Naganjaneya Lakshman                              Created
********************************************************************************/

public with sharing class DocumentController {
    @AuraEnabled(cacheable=true)
    public static void getRelatedFilesByRecordId() {

       

}
}